[package]
name = "lian-kernel"
version = "0.1.0"
edition = "2024"
description = "Lian - a top-tier microkernel written in Rust from scratch"
license = "MIT OR Apache-2.0"

[lib]
name = "lian"
path = "src/lib.rs"

[[bin]]
name = "lian-kernel"
path = "src/main.rs"

[profile.dev]
panic = "abort"
debug = true
opt-level = 1

[profile.release]
panic = "abort"
opt-level = 3
lto = true
codegen-units = 1
strip = false
